#!/bin/sh

export HANDBOOK_SQLDSN="$HANDBOOK_USER:$HANDBOOK_PASS@tcp($HANDBOOK_HOST:$HANDBOOK_PORT)/$HANDBOOK_DATABASE?parseTime=true"
export HANDBOOK_STAFFDBDSN="DRIVER={Progress};HostName=$SKYWARD_HOST;PORTNUMBER=$SKYWARD_PORT;DATABASENAME=$SKYWARD_DATABASE;LogonID=$SKYWARD_USER;PASSWORD=$SKYWARD_PASS"

exec $1
